#!/usr/bin/env python

import datetime
start = datetime.datetime.now()
from pandas import Series, DataFrame 
import pandas as pd
import csv
import pandas
import urllib.request
import re
import shutil, os
import numpy as np
from urllib.request import urlopen
from bs4 import BeautifulSoup
import sys
import requests
import warnings
warnings.filterwarnings("ignore")
import datetime
import subprocess

print('\n[ Functional Enrichment Analysis ]\n')
#print('▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n')
print('■  1  Gene Ontology Enrichment\n')
print('■  2  KEGG Pathways Enrichment\n')
print('■  3  KEGG Pathways Enrichment using blastp (*** Not enabled)')
#print('\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n')
a='b'
analysis=input('\n▬  Select an analysis (e.g., 1 / 2 / 3)\n=====> : ')
if float(analysis) == 1:
    enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/GO_api.py").content.decode()
    enrichment=open("enrichment.py","w")
    enrichment.write(enrich)
    enrichment.close()
else:
    if float(analysis) == 2:
        enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/K.py").content.decode()
        enrichment=open("enrichment.py","w")
        enrichment.write(enrich)
        enrichment.close()
    else:
        if float(analysis) == 3:
            #print('!!!!!!! Not enabled !!!!!!!')
            enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/K_Unch.py").content.decode()
            enrichment=open("enrichment.py","w")
            enrichment.write(enrich)
            enrichment.close()
        else:
            analysis=input('▬▬▬▬▬▬▬▬\nSelect an analysis correctly (e.g., 1 / 2 / 3)\n▬▬▬▬▬▬▬▬\n=====> : ')
            if float(analysis) == 1:
                enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/GO_api.py").content.decode()
                enrichment=open("enrichment.py","w")
                enrichment.write(enrich)
                enrichment.close()
            else:
                if float(analysis) == 2:
                    enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/K.py").content.decode()
                    enrichment=open("enrichment.py","w")
                    enrichment.write(enrich)
                    enrichment.close()
                else:
                    if float(analysis) == 3:
                        #print('!!!!!!! Not enabled !!!!!!!')
                        enrich=requests.get("https://raw.githubusercontent.com/bioinfproject/bioinfo/master/K_Unch.py").content.decode()
                        enrichment=open("enrichment.py","w")
                        enrichment.write(enrich)
                        enrichment.close()
                        print('\n!!!!!!! Analysis not found !!!!!!!\n')
                        sys.exit()
                        
subprocess.call(['python', 'enrichment.py'])

