#
install.packages("GetoptLong", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("tidyverse", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("tidygraph", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("ggraph", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("viridis", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("circlize", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("RColorBrewer", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("cowplot", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("networkD3", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("UpSetR", dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("gridBase",dependencies = TRUE,repos='http://cran.us.r-project.org')
install.packages("reshape2",dependencies = TRUE,repos='http://cran.us.r-project.org')
source("http://bioconductor.org/biocLite.R")
biocLite("ComplexHeatmap")
#
print("")
print("")
print("!!! All packages have been installed successfully!!!")
print("")
print("")
Sys.sleep(5)
